Add code for reading LED Sign
SCE-Development/Quasar pull request #2
Opened 2021-12-04 02:14 UTC by andrewtedi

reading rainbow

2021-12-04 02:46 UTC, allen-tran commented
you are so awesome at coding

2021-12-17 04:11 UTC, evanugarte requested changes

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +const hostname = 'X.X.X.X';
put host name and LED_URL in config.js

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +server.listen(port, hostname, () => {
I think you can remove all the server stuff. this file just listens for messages pushed on SQS and then acts accordingly.

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +      console.log(err, err.stack);
```suggestion
      return;
```

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +        console.log('Nothing to process');
```suggestion
```

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +      // orderData is now an object that contains order_id and date properties
remove these comments

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +}, 1000);
We will getting billed for querying the queue too much. let's do every 10 seconds instead
```suggestion
}, 10000);

```

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +      sqs.deleteMessage(deleteParams, (err, data) => {
you can remove the if/else below and just make it an empty function, later we can have smarter error handling

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +      // console.log("I am going to parse", data.Messages[0].Body);
```suggestion
```

2021-12-17 04:11 UTC, evanugarte commented on ledsign/sqsread.js
> +      console.log('Order received', orderData);
remove all console 🪵 
```suggestion
```

2021-12-17 08:05 UTC, evanugarte approved these changes

2021-12-26 23:56 UTC, allen-tran approved these changes

2021-12-26 23:59 UTC, merged