write to sqs
SCE-Development/Quasar pull request #71
Opened 2022-07-07 20:57 UTC by praveenksamy148

Upload file directly to aws s3 using node and send a queue to aws SQS

2022-07-07 22:33 UTC, neelp03 requested changes
:d

2022-07-07 22:33 UTC, neelp03 commented on util/writeToSQS.js
> +        Body: fs.readFileSync('./blank.pdf')
Why upload a pdf on local device?

2022-07-07 22:33 UTC, neelp03 commented on util/writeToSQS.js
> +            console.log('File uploaded successfully.');
instead of console logs, use the logger we have in Quasar/util/

2022-07-07 22:33 UTC, neelp03 commented on util/writeToSQS.js
> +        sqsParams.QueueUrl;
same here, use logger

2022-07-07 22:33 UTC, neelp03 commented on util/writeToSQS.js
> +sendQueue(fileNo);
need EOF

2022-07-07 22:33 UTC, neelp03 commented on util/writeToSQS.js
> +            fileName: fileNo,
```suggestion
            fileName: fileNo
```

2022-07-07 23:33 UTC, neelp03 commented
Also put writeToSQS in a new folder called tools

2022-07-09 01:24 UTC, neelp03 requested changes
for the functions you wrote can you add documentation in JS syntax please, that way if someone new were to come work on Core-v4, they would immediately understand what the function is doing without reading the body. Use these for reference:

[Inline JS Documentation Guide](https://developer.wordpress.org/coding-standards/inline-documentation-standards/javascript/)
[Documentation example in Core-v4](https://github.com/SCE-Development/Core-v4/blob/dev/api/peripheral_api/util/RFID-helpers.js#L10:L15)

2022-07-09 02:14 UTC, neelp03 approved these changes

2022-07-09 02:36 UTC, evanugarte commented on util/tools/writeToSQS.js
> +sendQueue(fileNo);
can we just make a function at the bottom called main which does:
```js
function main() {
  const fileNo = Math.random();
  uploadFile(fileNo);
  sendQueue(fileNo);
}

main();
```

2022-07-09 03:07 UTC, ShaivPandya approved these changes

2022-07-10 18:57 UTC, merged